### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jaberwalk** [CiscoUKIDCDev/HP3ParPlugin#1]
Great job with this plugin, excellent work!

Suggestions for features:
- Host Set creation / deletion
- Host creation / deletion
- Add / remove host to host set

**Comment by mattsday** [comment]
This should be easy to add and I'll target the next release (0.4.0) for this now that inventory persistence is working.

**Comment by mattsday** [comment]
Started on the initial work, hosts are now enumerated
![Hosts view screenshot](https://matt.fragilegeek.com/ucsd/3par-plugin-hosts)
![Hosts drilldown screenshot](https://matt.fragilegeek.com/ucsd/3par-plugin-hosts-drilldown)

Started on actions to create/delete/edit them and then will move on to mapping WWN/iSCSI names to them. After that will need to add export tasks to map virtual volumes to hosts.

Finally then host groups + volume groups.

**Comment by mattsday** [comment]
Added in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/d81d83c2ca9f93fe8112aa2e8b7b4051d311e0b0 - 0.4.0 release due soon

**Comment by jaberwalk** [comment]
Very awesome. We'll get this installed tomorrow and test it out!
