### ISSUE TITLE
ant build throws error

### ISSUE THREAD

**Issue by JeffJ45** [CiscoUKIDCDev/HP3ParPlugin#65]
hello, when running ant build in the 3Par_Plugin directory I receive the error message:

E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin>ant build
Buildfile: E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\build.xml

clean:

jdoEnhance:
     [java] ERROR: Compiled classes directory E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\bin not found
     [java] Java Result: 1

verify:
     [exec]   File "../ucsd-troubleshooter/SHOOTER.py", line 38
     [exec]     try:
     [exec]        ^
     [exec] TabError: inconsistent use of tabs and spaces in indentation

BUILD FAILED
E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\build.xml:60: exec returned: 1

Total time: 1 second

**Comment by JeffJ45** [comment]
After downgrading python the bin directory still seems to be an issue causing it to fail.

E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin>ant build
Buildfile: E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\build.xml

clean:

jdoEnhance:
     [java] ERROR: Compiled classes directory E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\bin not found
     [java] Java Result: 1

verify:
     [exec] WARNING:root:       public CollectorFactory[] getCollectors() returns null
     [exec]
     [exec]
     [exec]
     [exec]
     [exec]
     [exec] WARNING:root:       The following classes are not listed in a jdo.files for JDOEnhancement:
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\AddFCWWNHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\DeleteHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\account\HP3ParAccountDBStore
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\system\CollectInventoryConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\RemoveFCWWNHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\copy\CreateVolumeSnapshotConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\cpg\CreateCpgConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\cpg\EditCpgConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\CreateVolumeSetSnapshotConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\CreateHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\RenameVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\AddHostToHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\RemoveVolumeFromVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumes\EditVolumeConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\copy\CreateVolumeCopyConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\RenameHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\AddVolumeToVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumes\DeleteVolumeConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\vluns\CreateVlunConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\RemoveiSCSIHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\EditVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\CreateHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumes\GrowVolumeConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\DeleteHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\account\inventory\HP3ParInventoryDBStore
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\DeleteVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\AddiSCSIHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hosts\EditHostConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumesets\CreateVolumeSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\cpg\DeleteCpgConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\EditHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\hostsets\RemoveHostFromHostSetConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\vluns\DeleteVlunConfig
     [exec] WARNING:root:               src\com\cisco\matday\ucsd\hp3par\tasks\volumes\CreateVolumeConfig

build:
    [mkdir] Created dir: E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\build

BUILD FAILED
E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\build.xml:13: E:\3PAR\HP3ParPlugin-1.0.1a\3PAR_Plugin\bin does not exist.

Total time: 1 second

**Comment by mattsday** [comment]
I think this is because the ant script makes the assumption that it's running on a UNIX style system (e.g. Linux, MacOS, ...).

I've not tested it on Windows - does issuing this command first fix it?
```
mkdir bin
```

**Comment by mattsday** [comment]
Does this also happen in release 1.0.1? This release has a slightly different build process (which I will revert back to if it's causing compilation problems).

**Comment by JeffJ45** [comment]
I was able to compile using eclipse and commenting out




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mattsday** [comment]
I've patched the latest build so it only uses the python checking if it's a debug... this should fix this issue.
